on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - uses: RaPaLearning/write4u@v00
        with:
          vale-options: 'nothing yet'
      - run: echo "Done!"
        shell: bash
