on: [push]

jobs:
  linting-style:
    runs-on: ubuntu-latest
    name: Lint markdown with style
    steps:
      - uses: actions/checkout@v3
      - uses: RaPaLearning/write4u@v01
        with:
          vale-options: 'nothing yet'
      - run: echo "Done!"
        shell: bash
